spring:
  config:
    activate:
      on-profile: "local"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug