spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug